### ISSUE TITLE
Mobile responsive website

### ISSUE THREAD

**Issue by maenad** [babaiyu/indonesian_jokes#3]
Hello, I hope you are doing great.

Is it alright if I try a couple of fixes to make this website mobile-responsive?

![image](https://user-images.githubusercontent.com/31748140/136941258-c8c0e5e8-99c0-4b38-b724-32f510bae95b.png)

**Comment by babaiyu** [comment]
Absolutely find, i am really love for mobile responsive. Sorry i don't understand about responsive website, many lot of thanks for your fixes. Go a head @maenad

**Comment by maenad** [comment]
Great, I will be working on it later today! 

Can you please assign this issue to me?

Thanks in advance, have a great day.

**Comment by babaiyu** [comment]
Okay, i have added you

**Comment by maenad** [comment]
Hello! I have created a PR for this issue.

Would it be okay for you to add the Hacktoberfest tag to this? I have already completed my PRs, but just in case any of them gets pushed back, ahaha. If not, don't worry.

Happy week!
